ALTER TABLE profiles ADD COLUMN IF NOT EXISTS driver_lat FLOAT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS driver_lon FLOAT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS max_cargo_weight INTEGER;
